config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations' }
  root 'home#index'
  get 'home/index'
  get 'home/search'
  get 'home/:id/sortp' => "home#sort_p" ,:as =>"home_sortp"
  get 'home/:id/sortp_d'=>"home#sort_p_d",:as =>"home_sortpd"
  get 'users/:id' =>"home#mypage", :as =>"user_mypage"
  
  resources :sort
  resources :cp do
    resources :board  
    resources :reservation
    resources :nticket
  end
  
  put '/cp/:cp_id/reservation/:id/confirm'=>"reservation#confirm", :as =>"reservation_confirm"
  put '/cp/:cp_id/reservation/:id/reject'=>"reservation#reject", :as =>"reservation_reject"
  
  
  get 'phonegap_request/sort_request'
  get 'phonegap_request/login_request'
  
  get 'androidrequest/login_request'
  get 'androidrequest/sort_request'
  get 'androidrequest/company_request'
  get 'androidrequest/nticket_request'
  get 'androidrequest/reserve_request'
  get 'androidrequest/mypage_nticket_request'
  get 'androidrequest/mypage_reverse_request'
  get 'androidrequest/nfc_request'
  get 'androidrequest/nfcdel_request'

end

app/models/nticket.rb
class Nticket < ActiveRecord::Base
    belongs_to :user
    belongs_to :company
end

app/controllers/nticket_controller.rb
class NticketController < ApplicationController
  def index
    # nticket_indexs는 업체 관리 페이지로 사용할 것
    
    @ntickets = Nticket.where(:company_id => params[:cp_id])
    
  end

  def create
    nticket = Nticket.new
    if params[:user_name] == nil
      nticket.user_id = current_user.id
    end
    nticket.company_id = params[:cp_id]
    unless params[:user_name] == nil
      nticket.user_name = params[:user_name]
      nticket.user_phone = params[:user_phone]
    end
    @nticket_max = Company.find(params[:cp_id]).nticket_max
    
    nticket.ticketnumber = @nticket_max
    nticket.save
    
    company = Company.find(params[:cp_id])
    company.nticket_max += 1
    company.save
    
    redirect_to cp_path(params[:cp_id])
  end

  def new
  end

  def edit
  end

  def show
  end

  def update
  end

  def destroy
    
    Nticket.find(params[:id]).destroy
    
    redirect_to cp_nticket_index_path(params[:cp_id])
  end
end

app/helpers/nticket_helper.rb
module NticketHelper
end

app/views/nticket/edit.html.erb
<h1>Nticket#edit</h1>
<p>Find me in app/views/nticket/edit.html.erb</p>

app/views/nticket/index.html.erb
<%= link_to "예약관리", cp_reservation_index_path(params[:cp_id]) %></br>
<%= link_to "현장에서 번호표 뽑기", new_cp_nticket_path(params[:cp_id]) %>
</br>
<%= hidden_field_tag(:company_id, params[:cp_id]) %>
번호표</br>
<% @ntickets.each do |n| %>
    <% unless n.user_id == nil %>
        <%= n.ticketnumber %>번 <%= n.user.name %>님 
        <button class="nticket_complete" value="<%= n.id %>">승인</button></br>
    <% else %>
        <%= n.ticketnumber %>번 <%= n.user_name %>님 
        <button class="nticket_complete" value="<%= n.id %>">승인</button></br>
    <% end %>
<% end %>


<script>
    $(".nticket_complete").click(function(){
        var cp_id = $("#company_id").val();
        var id = this.value;
       $.ajax({
            url:'/cp/'+cp_id+'/nticket/'+id,
            method:"DELETE",
            data:{},
            success:function(data){
                alert("승인되었습니다.");
            },
            error:function(){
                alert("승인되지않았습니다.");
             }
        })
    });
</script>

app/views/nticket/new.html.erb
<%= form_tag(controller: "nticket", action: "create", method: "post") do %>
    <%= label_tag(:user_name, "이름") %>
    <%= text_field_tag :user_name ,nil, :placeholder =>"이름을 입력해주세요." %></br>
    <%= label_tag(:user_phone, "전화번호") %>
    <%= text_field_tag :user_phone ,nil, :placeholder =>"전화번호를 입력해주세요." %></br>
    
    <%= submit_tag("번호표 뽑기") %>
<% end %>

app/views/nticket/show.html.erb
<h1>Nticket#show</h1>
<p>Find me in app/views/nticket/show.html.erb</p>