config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations' }
  root 'home#index'
  get 'home/index'
  get 'home/search'
  get 'home/:id/sortp' => "home#sort_p" ,:as =>"home_sortp"
  get 'home/:id/sortp_d'=>"home#sort_p_d",:as =>"home_sortpd"
  get 'users/:id' =>"home#mypage", :as =>"user_mypage"
  
  resources :sort
  resources :cp do
    resources :board  
    resources :reservation
    resources :nticket
  end
  
  put '/cp/:cp_id/reservation/:id/confirm'=>"reservation#confirm", :as =>"reservation_confirm"
  put '/cp/:cp_id/reservation/:id/reject'=>"reservation#reject", :as =>"reservation_reject"
  
  
  get 'phonegap_request/sort_request'
  get 'phonegap_request/login_request'
  
  get 'androidrequest/login_request'
  get 'androidrequest/sort_request'
  get 'androidrequest/company_request'
  get 'androidrequest/nticket_request'
  get 'androidrequest/reserve_request'
  get 'androidrequest/mypage_nticket_request'
  get 'androidrequest/mypage_reverse_request'
  get 'androidrequest/nfc_request'
  get 'androidrequest/nfcdel_request'

end

app/models/board.rb
class Board < ActiveRecord::Base
    belongs_to :company
    belongs_to :user
end

app/models/company.rb
class Company < ActiveRecord::Base
    belongs_to :csort
    has_many :boards
    has_many :reservations
    has_many :ntickets
end

app/models/csort.rb
class Csort < ActiveRecord::Base
    has_many :companies
end

app/models/nticket.rb
class Nticket < ActiveRecord::Base
    belongs_to :user
    belongs_to :company
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
    belongs_to :user
    belongs_to :company
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  
  has_many :boards
  has_many :reservations
  has_many :ntickets
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  
  protect_from_forgery with: :null_session, if: ->{request.format.json?}
end

app/controllers/board_controller.rb
class BoardController < ApplicationController
  def index
  end

  def create
    board = Board.new(title: params[:title], content: params[:content], company_id: params[:company_id].to_i, user_id: current_user.id, star: params[:rating])
    uploader = KjarUploader.new
    file = params[:pic]
    uploader.store!(file)
    board.image_url = uploader.url
    if board.save
      redirect_to cp_path(params[:cp_id])
    else
      render :text => board.errors.messages
    end
  end

  def new
    @board = Board.new
    if user_signed_in?
      
    else
      redirect_to new_user_session_path
    end
  end

  def edit
  end

  def show
    @board = Board.find(params[:id])
  end

  def update
  end

  def destroy
  end
end

app/controllers/cp_controller.rb
class CpController < ApplicationController
  def index
    @companies = Company.all
  end

  def create
    company = Company.new
    company.name = params[:name]
    company.c_postcode = params[:c_postcode]
    company.c_address = params[:c_address]
    company.c_daddress = params[:c_daddress]
    company.tel = params[:tel]
    company.opentime = params[:opentime]
    company.closetime = params[:closetime]
    company.runtime = params[:runtime].to_i * 60
    company.csort_id = params[:csort_id]
    company.save
    
    redirect_to cp_index_path
  end

  def new
    @csorts = Csort.all
    @company = Company.new
  end

  def edit
    @company = Company.find_by_id(params[:id])
  end

  def show
    @company = Company.find_by_id(params[:id])
    
    @boards = Board.where(:company_id => params[:id]).reverse
    
    @nticket = Nticket.where(:company_id => params[:id])
    if user_signed_in?
      @nticket2 = @nticket.where(:user_id => current_user.id)[0]
    end
  end

  def update
    company = Company.find_by_id(params[:id])
    company.name = params[:name]
    company.c_postcode = params[:c_postcode]
    company.c_address = params[:c_address]
    company.c_daddress = params[:c_daddress]
    company.tel = params[:tel]
    company.opentime = params[:opentime]
    company.closetime = params[:closetime]
    company.runtime = params[:runtime].to_i * 60
    company.save
    
    redirect_to cp_index_path
  end

  def destroy
    Company.find_by_id(params[:id]).destroy
    
    redirect_to cp_index_path
  end
  
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @sorts = Csort.all
  end
  
  def search
    @lat = params[:latitude]
    @lng = params[:longitude]
    @c_name = params[:c_name]
    companies = Company.where("name LIKE ?","%#{@c_name}%")
    distance_hash(@lat, @lng, *companies)
    
    @companies_hash = @companies_hash.sort_by {|name,companies_d| companies_d }
  end
  
  def sort_p
    @companies = Company.where(:csort_id => params[:id])
    
  end
  
  def sort_p_d
    companies = Company.where(:csort_id => params[:id])
    @lat = params[:latitude]
    @lng = params[:longitude]
    
    distance_hash(@lat, @lng, *companies)
    
    @companies_hash = @companies_hash.sort_by {|name,companies_d| companies_d }
  end
  
  def mypage
    @user = User.find(params[:id])
    
    @reservations = @user.reservations
    @ntickets = @user.ntickets
    
    
    
  end
  
  private
  def distance_hash(latitude,longitude,*companies)
    @lat = latitude
    @lng = longitude
    @companies = *companies
    @companies_hash  = Hash.new
    @companies_d ||= []
    @companies_a ||= []
    @rad_per_deg = Math::PI / 180
    @rm = 6371000 
    @companies.each do |c| 
      @lat1_rad, @lat2_rad = c.com_lat.to_f * @rad_per_deg, @lat.to_f * @rad_per_deg 
      @lon1_rad, @lon2_rad = c.com_lng.to_f * @rad_per_deg,@lng.to_f  * @rad_per_deg
      @a = Math.sin((@lat2_rad - @lat1_rad) / 2) ** 2 + Math.cos(@lat1_rad) * Math.cos(@lat2_rad) * Math.sin((@lon2_rad - @lon1_rad) / 2) ** 2 
      @c = 2 * Math::atan2(Math::sqrt(@a), Math::sqrt(1 - @a))

      @companies_hash[:"#{c.name}"] = (@rm * @c).to_i
    end
    
    return @companies_hash
    
  end
  
  
end

app/controllers/nticket_controller.rb
class NticketController < ApplicationController
  def index
    # nticket_indexs는 업체 관리 페이지로 사용할 것
    
    @ntickets = Nticket.where(:company_id => params[:cp_id])
    
  end

  def create
    nticket = Nticket.new
    if params[:user_name] == nil
      nticket.user_id = current_user.id
    end
    nticket.company_id = params[:cp_id]
    unless params[:user_name] == nil
      nticket.user_name = params[:user_name]
      nticket.user_phone = params[:user_phone]
    end
    @nticket_max = Company.find(params[:cp_id]).nticket_max
    
    nticket.ticketnumber = @nticket_max
    nticket.save
    
    company = Company.find(params[:cp_id])
    company.nticket_max += 1
    company.save
    
    redirect_to cp_path(params[:cp_id])
  end

  def new
  end

  def edit
  end

  def show
  end

  def update
  end

  def destroy
    
    Nticket.find(params[:id]).destroy
    
    redirect_to cp_nticket_index_path(params[:cp_id])
  end
end

app/controllers/sort_controller.rb
class SortController < ApplicationController
  def index
    @csorts = Csort.all
  end

  def create
    csort = Csort.new
    csort.name = params[:name]
    csort.save
    
    redirect_to sort_index_path
  end

  def new
  end

  def edit
    @csort = Csort.find_by_id(params[:id])
  end

  def show
    @csort = Csort.find_by_id(params[:id])
  end

  def update
    csort = Csort.find_by_id(params[:id])
    csort.name = params[:name]
    csort.save
    
    redirect_to sort_index_path
  end

  def destroy
    
    @company = Company.all
    @company.each do |c| 
      if c.csort_id == params[:id].to_i
          Company.find_by_id(c.id).destroy
      end
    end
    Csort.find_by_id(params[:id]).destroy
    redirect_to sort_index_path
  end
end

app/helpers/androidrequest_helper.rb
module AndroidrequestHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/board_helper.rb
module BoardHelper
end

app/helpers/cp_helper.rb
module CpHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/nticket_helper.rb
module NticketHelper
end

app/helpers/phonegap_request_helper.rb
module PhonegapRequestHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/reservation_helper.rb
module ReservationHelper
end

app/helpers/sort_helper.rb
module SortHelper
end

app/views/cp/edit.html.erb
<%= form_tag({controller: "cp", action: "update"}, method: "put") do %>
    <%= label_tag(:name, "업소명") %>
    <%= text_field_tag :name ,@company.name, :placeholder =>"업소명을 입력해주세요." %></br>
    <%= label_tag(:c_postcode, "우편번호") %>
    <%= text_field_tag :c_postcode ,@company.c_postcode, :placeholder =>"우편번호를 입력해주세요." %></br>
    <%= label_tag(:c_address, "주소") %>
    <%= text_field_tag :c_address ,@company.c_address, :placeholder =>"주소를 입력해주세요." %></br>
    <%= label_tag(:c_daddress, "상세주소") %>
    <%= text_field_tag :c_daddress ,@company.c_daddress, :placeholder =>"상세주소를 입력해주세요." %></br>
    <%= label_tag(:tel, "전화번호") %>
    <%= text_field_tag :tel ,@company.tel, :placeholder =>"전화번호를 입력해주세요." %></br>
    <%= label_tag(:opentime, "오픈시간") %>
    <%= text_field_tag :opentime ,@company.opentime, :placeholder =>"오픈시간을 입력해주세요." %></br>
    <%= label_tag(:closetime, "마감시간") %>
    <%= text_field_tag :closetime ,@company.closetime, :placeholder =>"마감시간을 입력해주세요." %></br>
    <%= label_tag(:runtime, "runtime") %>
    <%= text_field_tag :runtime ,(@company.runtime)/60, :placeholder =>"1팀 당 소요 시간을 입력해주세요." %>분</br>
    <%= submit_tag("수정") %>
<% end %>

app/views/cp/index.html.erb
<%= link_to "업체 추가", new_cp_path %></br>

<% @companies.each do |c| %>
    <%= link_to c.name, cp_path(c) %></br>
<% end %>

app/views/cp/new.html.erb
<%= form_tag(controller: "cp", action: "create", method: "post") do %>
    <%= label_tag(:name, "업소명") %>
    <%= text_field_tag :name ,nil, :placeholder =>"업소명을 입력해주세요." %></br>
    <%= label_tag(:c_postcode, "우편번호") %>
    <%= text_field_tag :c_postcode ,nil, :placeholder =>"우편번호를 입력해주세요." %></br>
    <%= label_tag(:c_address, "주소") %>
    <%= text_field_tag :c_address ,nil, :placeholder =>"주소를 입력해주세요." %></br>
    <%= label_tag(:c_daddress, "상세주소") %>
    <%= text_field_tag :c_daddress ,nil, :placeholder =>"상세주소를 입력해주세요." %></br>
    <%= label_tag(:tel, "전화번호") %>
    <%= text_field_tag :tel ,nil, :placeholder =>"전화번호를 입력해주세요." %></br>
    <%= label_tag(:opentime, "오픈시간") %>
    <%= text_field_tag :opentime ,nil, :placeholder =>"오픈시간을 입력해주세요." %></br>
    <%= label_tag(:closetime, "마감시간") %>
    <%= text_field_tag :closetime ,nil, :placeholder =>"마감시간을 입력해주세요." %></br>
    <%= label_tag(:runtime, "runtime") %>
    <%= text_field_tag :runtime ,nil, :placeholder =>"1팀 당 소요 시간을 입력해주세요." %>분</br>
    <%= label_tag(:csort_id, "분류") %>
    <%= select_tag 'csort_id', options_for_select(@csorts.collect{ |c| [c.name, c.id] }) %></br>
    <%= submit_tag("등록") %>
<% end %>

app/views/home/index.html.erb
<div class="position">
    <button type="button" onclick="requestPosition()" class="position-btn"></button>
    <div id="message"></div>
</div>
<%= form_tag({controller: "home", action: "search"}, method: "get",class:"search-form") do %>
    <%= hidden_field_tag (:latitude ) %>
    <%= hidden_field_tag (:longitude) %>
    <%= text_field_tag :c_name ,nil, :placeholder =>"업소명을 입력해주세요." , class:"search-box"%>
    <%= submit_tag("검색",class:"search-submit") %>
<% end %>

<ul class="ch-grid">
	<li>
		<div class="ch-item ch-img-1">
			<div class="ch-info">
			    
				<h3><%= link_to "분식", home_sortp_path(1) %></h3>
				<!--<p>병원 <%= link_to "분식",home_sortp_path(1) %></p>-->
			</div>
		</div>
	</li>
	<li>
		<div class="ch-item ch-img-2">
			<div class="ch-info">
				<h3><%= link_to "야식", home_sortp_path(2) %></h3>
				
			</div>
		</div>
	</li>
	<li>
		<div class="ch-item ch-img-3">
			<div class="ch-info">
				<h3><%= link_to "중식", home_sortp_path(3) %></h3>
				
			</div>
		</div>
	</li>
	<li>
		<div class="ch-item ch-img-4">
			<div class="ch-info">
				<h3><%= link_to "한식", home_sortp_path(4) %></h3>
				
			</div>
		</div>
	</li>
</ul>

<script>
    function setText(val, e) {
        document.getElementById(e).value = val;
    }
    
    function insertText(val, e) {
        document.getElementById(e).value += val;
    }
    
    var nav = null; 
    
    function requestPosition() {
      if (nav == null) {
          nav = window.navigator;
      }
      if (nav != null) {
          var geoloc = nav.geolocation;
          if (geoloc != null) {
              geoloc.getCurrentPosition(successCallback);
          }
          else {
              alert("geolocation not supported");
          }
      }
      else {
          alert("Navigator not found");
      }
    }


    function successCallback(position)
        {
           setText(position.coords.latitude, "latitude");
           setText(position.coords.longitude, "longitude");
        
        var lat = position.coords.latitude; // 위도
        var lng = position.coords.longitude; // 경도
        var geocode = "https://maps.googleapis.com/maps/api/geocode/json?latlng="+lat+","+lng;
        jQuery.ajax({
            url: geocode,
            type: 'POST',
               success: function(myJSONResult){
                        if(myJSONResult.status == 'OK') {
                            var tag = "";
                            var i;
                             tag += myJSONResult.results[0].formatted_address+" <br />";
                            
                            document.getElementById("message").innerHTML = tag;
                        } else if(myJSONResult.status == 'ZERO_RESULTS') {
                            alert("지오코딩이 성공했지만 반환된 결과가 없음을 나타냅니다.\n\n이는 지오코딩이 존재하지 않는 address 또는 원격 지역의 latlng을 전달받는 경우 발생할 수 있습니다.")
                        } else if(myJSONResult.status == 'OVER_QUERY_LIMIT') {
                            alert("할당량이 초과되었습니다.");
                        } else if(myJSONResult.status == 'REQUEST_DENIED') {
                            alert("요청이 거부되었습니다.\n\n대부분의 경우 sensor 매개변수가 없기 때문입니다.");
                        } else if(myJSONResult.status == 'INVALID_REQUEST') {
                            alert("일반적으로 쿼리(address 또는 latlng)가 누락되었음을 나타냅니다.");
                        }
                }
        });
     
    
    googleapisView();
    
        }
</script>

app/views/home/mypage.html.erb
<div class="mypage-nav">
    <div class="mypage_infor"><p class="btn" rel="div1">정보</p></div>
    <div class="mypage_nticket"><p class="btn" rel="div2">번호표</p></div>
    <div class="mypage_reservation"><p class="btn" rel="div3">예약</p></div>
</div>
<div id="div1"  class="mypage_div">
    <%= @user.email %>
    <%= @user.name %>
    <%= @user.phone%>
</div>

<div id="div2"  class="mypage_div" style="display:none;">
    <table>
        <tr>
            <th>업체</th>
            <th>번호표</th>
            <th>뽑은시간</th>
            <th>남은인원</th>
            <th>예상시간</th>
            <th>취소</th>
            <th>추천</th>
        </tr>
        <% @ntickets.each do |n| %>
            <tr>
                <td><%= Company.find(n.company_id).name %></td>
                <td><%= n.ticketnumber %>번</td>
                <td><%= (n.created_at + 32400).strftime("%H:%M:%S") %></td>
                <td></td>
                <td></td>
                <td></td>
                <td></td>
            </tr>
        <% end %>
    </table>
    
       
</div>

<div id="div3"  class="mypage_div" style="display:none;">
    <% @reservations.each do |r| %>
        <%= Company.find(r.company_id).name %> 
        <%= r.reserve_time %> 
        <%= r.reserve_date %> 
        <%= link_to "자세히 보기",cp_reservation_path(r.company_id,r.id)%></br>
    <% end %></br>
</div>

<script>
    $('p').on('click', function(){
     var target = $(this).attr('rel');
     $("#"+target).show().siblings(".mypage_div").hide();
     
  });
</script>

app/views/home/search.html.erb
'<%=@c_name %>' 검색 결과</br>
<% if @companies.length >0 %>
    <% unless @lat == "" %>
        <% @companies_hash.each do |h,d| %>
            <%= h %>  <%= d*0.001 %>km </br>
        <% end %>    
    <% else %>
        <% @companies.each do |c| %>
        <%=link_to c.name,cp_path(c.id) %></br>
        <% end %>
    <% end %>
<% else %>
    검색 결과가 없습니다.
<% end %>

app/views/home/sort_p.html.erb
<div class="position">
    <div id="message"></div>
</div>
<%= form_tag({controller: "home", action: "sort_p_d"}, method: "get",class:"search-form") do %>
    <%= hidden_field_tag (:latitude ) %>
    <%= hidden_field_tag (:longitude) %>
    <%= submit_tag("거리순 보기",class:"search-submit",onclick:"requestPosition()") %>
<% end %>


<% @companies.each do |c| %>
    <%=link_to c.name,cp_path(c.id) %></br>
<% end %>

<script>
    function setText(val, e) {
        document.getElementById(e).value = val;
    }
    
    function insertText(val, e) {
        document.getElementById(e).value += val;
    }
    
    var nav = null; 
    
    function requestPosition() {
      if (nav == null) {
          nav = window.navigator;
      }
      if (nav != null) {
          var geoloc = nav.geolocation;
          if (geoloc != null) {
              geoloc.getCurrentPosition(successCallback);
          }
          else {
              alert("geolocation not supported");
          }
      }
      else {
          alert("Navigator not found");
      }
    }


    function successCallback(position)
        {
           setText(position.coords.latitude, "latitude");
           setText(position.coords.longitude, "longitude");
        
        var lat = position.coords.latitude; // 위도
        var lng = position.coords.longitude; // 경도
        var geocode = "https://maps.googleapis.com/maps/api/geocode/json?latlng="+lat+","+lng;
        jQuery.ajax({
            url: geocode,
            type: 'POST',
               success: function(myJSONResult){
                        if(myJSONResult.status == 'OK') {
                            var tag = "";
                            var i;
                             tag += myJSONResult.results[0].formatted_address+" <br />";
                            
                            document.getElementById("message").innerHTML = tag;
                        } else if(myJSONResult.status == 'ZERO_RESULTS') {
                            alert("지오코딩이 성공했지만 반환된 결과가 없음을 나타냅니다.\n\n이는 지오코딩이 존재하지 않는 address 또는 원격 지역의 latlng을 전달받는 경우 발생할 수 있습니다.")
                        } else if(myJSONResult.status == 'OVER_QUERY_LIMIT') {
                            alert("할당량이 초과되었습니다.");
                        } else if(myJSONResult.status == 'REQUEST_DENIED') {
                            alert("요청이 거부되었습니다.\n\n대부분의 경우 sensor 매개변수가 없기 때문입니다.");
                        } else if(myJSONResult.status == 'INVALID_REQUEST') {
                            alert("일반적으로 쿼리(address 또는 latlng)가 누락되었음을 나타냅니다.");
                        }
                }
        });
     
    
    googleapisView();
    
        }
</script>

app/views/home/sort_p_d.html.erb
거리순 보기</br>

<% @companies_hash.each do |n,v| %>
    <%= n %> <%= v * 0.001 %>km</br>
<% end %>

app/views/sort/edit.html.erb
<%= form_tag({controller: "sort", action: "update"}, method: "put") do %>
    <%= label_tag(:name, "분류 이름") %>
    <%= text_field_tag :name ,@csort.name, :placeholder =>"분류 이름을 입력해주세요." %>
   
    <%= submit_tag("추가") %>
<% end %>

app/views/sort/index.html.erb
<%= link_to "분류 추가하기", new_sort_path %></br>

<% @csorts.each do |c| %>
    <%= link_to c.name, sort_path(c) %> </br>
<% end %>

app/views/sort/new.html.erb
<%= form_tag(controller: "sort", action: "create", method: "post") do %>
    <%= label_tag(:name, "분류 이름") %>
    <%= text_field_tag :name ,nil, :placeholder =>"분류 이름을 입력해주세요." %>
   
    <%= submit_tag("추가") %>
<% end %>

app/views/sort/show.html.erb
<%= @csort.name %></br>
<%= link_to "수정", edit_sort_path(@csort.id) %></br>
<%= link_to "삭제", sort_path(@csort.id), :method => "delete" %></br>