config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations' }
  root 'home#index'
  get 'home/index'
  get 'home/search'
  get 'home/:id/sortp' => "home#sort_p" ,:as =>"home_sortp"
  get 'home/:id/sortp_d'=>"home#sort_p_d",:as =>"home_sortpd"
  get 'users/:id' =>"home#mypage", :as =>"user_mypage"
  
  resources :sort
  resources :cp do
    resources :board  
    resources :reservation
    resources :nticket
  end
  
  put '/cp/:cp_id/reservation/:id/confirm'=>"reservation#confirm", :as =>"reservation_confirm"
  put '/cp/:cp_id/reservation/:id/reject'=>"reservation#reject", :as =>"reservation_reject"
  
  
  get 'phonegap_request/sort_request'
  get 'phonegap_request/login_request'
  
  get 'androidrequest/login_request'
  get 'androidrequest/sort_request'
  get 'androidrequest/company_request'
  get 'androidrequest/nticket_request'
  get 'androidrequest/reserve_request'
  get 'androidrequest/mypage_nticket_request'
  get 'androidrequest/mypage_reverse_request'
  get 'androidrequest/nfc_request'
  get 'androidrequest/nfcdel_request'

end

app/models/board.rb
class Board < ActiveRecord::Base
    belongs_to :company
    belongs_to :user
end

app/models/company.rb
class Company < ActiveRecord::Base
    belongs_to :csort
    has_many :boards
    has_many :reservations
    has_many :ntickets
end

app/models/csort.rb
class Csort < ActiveRecord::Base
    has_many :companies
end

app/models/nticket.rb
class Nticket < ActiveRecord::Base
    belongs_to :user
    belongs_to :company
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
    belongs_to :user
    belongs_to :company
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  
  has_many :boards
  has_many :reservations
  has_many :ntickets
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/board_controller.rb
class BoardController < ApplicationController
  def index
  end

  def create
    board = Board.new(title: params[:title], content: params[:content], company_id: params[:company_id].to_i, user_id: current_user.id, star: params[:rating])
    uploader = KjarUploader.new
    file = params[:pic]
    uploader.store!(file)
    board.image_url = uploader.url
    if board.save
      redirect_to cp_path(params[:cp_id])
    else
      render :text => board.errors.messages
    end
  end

  def new
    @board = Board.new
    if user_signed_in?
      
    else
      redirect_to new_user_session_path
    end
  end

  def edit
  end

  def show
    @board = Board.find(params[:id])
  end

  def update
  end

  def destroy
  end
end

app/controllers/cp_controller.rb
class CpController < ApplicationController
  def index
    @companies = Company.all
  end

  def create
    company = Company.new
    company.name = params[:name]
    company.c_postcode = params[:c_postcode]
    company.c_address = params[:c_address]
    company.c_daddress = params[:c_daddress]
    company.tel = params[:tel]
    company.opentime = params[:opentime]
    company.closetime = params[:closetime]
    company.runtime = params[:runtime].to_i * 60
    company.csort_id = params[:csort_id]
    company.save
    
    redirect_to cp_index_path
  end

  def new
    @csorts = Csort.all
    @company = Company.new
  end

  def edit
    @company = Company.find_by_id(params[:id])
  end

  def show
    @company = Company.find_by_id(params[:id])
    
    @boards = Board.where(:company_id => params[:id]).reverse
    
    @nticket = Nticket.where(:company_id => params[:id])
    if user_signed_in?
      @nticket2 = @nticket.where(:user_id => current_user.id)[0]
    end
  end

  def update
    company = Company.find_by_id(params[:id])
    company.name = params[:name]
    company.c_postcode = params[:c_postcode]
    company.c_address = params[:c_address]
    company.c_daddress = params[:c_daddress]
    company.tel = params[:tel]
    company.opentime = params[:opentime]
    company.closetime = params[:closetime]
    company.runtime = params[:runtime].to_i * 60
    company.save
    
    redirect_to cp_index_path
  end

  def destroy
    Company.find_by_id(params[:id]).destroy
    
    redirect_to cp_index_path
  end
  
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @sorts = Csort.all
  end
  
  def search
    @lat = params[:latitude]
    @lng = params[:longitude]
    @c_name = params[:c_name]
    companies = Company.where("name LIKE ?","%#{@c_name}%")
    distance_hash(@lat, @lng, *companies)
    
    @companies_hash = @companies_hash.sort_by {|name,companies_d| companies_d }
  end
  
  def sort_p
    @companies = Company.where(:csort_id => params[:id])
    
  end
  
  def sort_p_d
    companies = Company.where(:csort_id => params[:id])
    @lat = params[:latitude]
    @lng = params[:longitude]
    
    distance_hash(@lat, @lng, *companies)
    
    @companies_hash = @companies_hash.sort_by {|name,companies_d| companies_d }
  end
  
  def mypage
    @user = User.find(params[:id])
    
    @reservations = @user.reservations
    @ntickets = @user.ntickets
    
    
    
  end
  
  private
  def distance_hash(latitude,longitude,*companies)
    @lat = latitude
    @lng = longitude
    @companies = *companies
    @companies_hash  = Hash.new
    @companies_d ||= []
    @companies_a ||= []
    @rad_per_deg = Math::PI / 180
    @rm = 6371000 
    @companies.each do |c| 
      @lat1_rad, @lat2_rad = c.com_lat.to_f * @rad_per_deg, @lat.to_f * @rad_per_deg 
      @lon1_rad, @lon2_rad = c.com_lng.to_f * @rad_per_deg,@lng.to_f  * @rad_per_deg
      @a = Math.sin((@lat2_rad - @lat1_rad) / 2) ** 2 + Math.cos(@lat1_rad) * Math.cos(@lat2_rad) * Math.sin((@lon2_rad - @lon1_rad) / 2) ** 2 
      @c = 2 * Math::atan2(Math::sqrt(@a), Math::sqrt(1 - @a))

      @companies_hash[:"#{c.name}"] = (@rm * @c).to_i
    end
    
    return @companies_hash
    
  end
  
  
end

app/controllers/nticket_controller.rb
class NticketController < ApplicationController
  def index
    # nticket_indexs는 업체 관리 페이지로 사용할 것
    
    @ntickets = Nticket.where(:company_id => params[:cp_id])
    
  end

  def create
    nticket = Nticket.new
    if params[:user_name] == nil
      nticket.user_id = current_user.id
    end
    nticket.company_id = params[:cp_id]
    unless params[:user_name] == nil
      nticket.user_name = params[:user_name]
      nticket.user_phone = params[:user_phone]
    end
    @nticket_max = Company.find(params[:cp_id]).nticket_max
    
    nticket.ticketnumber = @nticket_max
    nticket.save
    
    company = Company.find(params[:cp_id])
    company.nticket_max += 1
    company.save
    
    redirect_to cp_path(params[:cp_id])
  end

  def new
  end

  def edit
  end

  def show
  end

  def update
  end

  def destroy
    
    Nticket.find(params[:id]).destroy
    
    redirect_to cp_nticket_index_path(params[:cp_id])
  end
end

app/controllers/sort_controller.rb
class SortController < ApplicationController
  def index
    @csorts = Csort.all
  end

  def create
    csort = Csort.new
    csort.name = params[:name]
    csort.save
    
    redirect_to sort_index_path
  end

  def new
  end

  def edit
    @csort = Csort.find_by_id(params[:id])
  end

  def show
    @csort = Csort.find_by_id(params[:id])
  end

  def update
    csort = Csort.find_by_id(params[:id])
    csort.name = params[:name]
    csort.save
    
    redirect_to sort_index_path
  end

  def destroy
    
    @company = Company.all
    @company.each do |c| 
      if c.csort_id == params[:id].to_i
          Company.find_by_id(c.id).destroy
      end
    end
    Csort.find_by_id(params[:id]).destroy
    redirect_to sort_index_path
  end
end

app/helpers/androidrequest_helper.rb
module AndroidrequestHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/board_helper.rb
module BoardHelper
end

app/helpers/cp_helper.rb
module CpHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/nticket_helper.rb
module NticketHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/reservation_helper.rb
module ReservationHelper
end

app/helpers/sort_helper.rb
module SortHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link type="text/css" rel="stylesheet" href="/main.css?ver=1" />
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
  <!--
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBM3uk40DW7g5LuX1zzdPIfTWK7NBuf3Q0"
        async defer></script>
        -->
  <script src="/jquery.timepicker.js"></script>
  <link type="text/css" rel="stylesheet" href="/jquery.timepicker.css" />
  <script src="/jquery.simplemodal.js"></script>
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBM3uk40DW7g5LuX1zzdPIfTWK7NBuf3Q0"
        async defer></script>
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">


</head>
<body>
  <nav class="navbar" role="navigation">
    
    <div class="div-user">
      <ul class="div-user-ul">
        <div class="nav-div"></div>
        
        <div class="nav-user">
          <% if user_signed_in? %>
            <li><%= current_user.email   %>님</li>
            <li><%= link_to "마이페이지", user_mypage_path(current_user.id)%></li>
            <li><%= link_to('로그아웃', destroy_user_session_path, :method => "delete") %></li>  
            
          <% else %>
            <li><%= link_to "로그인", new_user_session_path %></li>
          <% end %>
        </div>
        <div class="nav-button">
          <img src="/image/a.png" class="nav-button-img"/>
        </div>
        <div class="nav-toggle" style="display:none">
          <span>
            <img src="/image/dir.png" />
          </span>
          <ul>
            <% if user_signed_in? %>
            <li><%= current_user.email   %>님</li>
            <li><%= link_to "마이페이지", user_mypage_path(current_user.id) %></li>
            <li><%= link_to('로그아웃', destroy_user_session_path, :method => "delete") %></li>  
            
          <% else %>
            <li><%= link_to "로그인", new_user_session_path %></li>
          <% end %>
          <li><a href="#">공지사항</a></li>
          <li><a href="#">Q&A</a></li>
          </ul>
        </div>
      </ul>
    </div>
  </nav>
  <header>
    <div class="logoimg-class" id="logoimg-id">
      <%= link_to root_path do %>
        <h1><%= image_tag "/image/logo.png", alt:"logo", id:"logoimg" %></h1>
      <% end %>
    </div>
  </header>
  <section>
    <div class="container">
      <%= yield %>
    </div>
  </section>
  <footer>
    <p>Copyright &copy; 권진아리</p>
  </footer>
  <script>
    $(".nav-button-img").click(function(){
      $(".nav-toggle").slideDown();
      
    });
    
    $(".nav-toggle span img").click(function(){
      $(".nav-toggle").slideUp();
    })
  </script>
</body>
</html>